### ISSUE TITLE
OSError on launch

### ISSUE THREAD

**Issue by eoakley** [nickzuber/chs#1]
Hi, got the following error after running on Ubuntu Server 18.04. Installation was ok.

Uncaught error "OSError", exiting the app.

**Comment by nickzuber** [comment]
Hmm I suspect this has to do with the Stockfish engine binary — it might be only compatible with Mac OS. 

I wonder if a good way to fix this would be to provide a variety of binaries and select the correct one based on OS detection

**Comment by eoakley** [comment]
Yes, that is the issue. I'm implementing this, will commit soon.

Thanks

**Comment by enormandeau** [comment]
I'm having the same error on Linux. If there is a fix I'd be glad to try this!

**Comment by cjennings** [comment]
Same issue on Debian Buster with Stockfish 11. Would be happy to help test a fix, or workaround.

**Comment by nickzuber** [comment]
This bug was patched in https://github.com/nickzuber/chs/pull/2 and I released the latest version of the project just now.

Things should be fixed — please let me know if you guys are running into the same issue

**Comment by PaxiTheAlchemist** [comment]
Currently having this exact issue on a Raspberry Pi 3 Model B+ running Ubuntu 18.04.6 LTS armv7l. Unsure whether it can run on Arm or the Pi for the matter, however, it seems to install just fine. I am currently running on version 3.0.0 of Chs, the latest at the time of sending this
