### ISSUE TITLE
Need a new release - FileNotFoundError

### ISSUE THREAD

**Issue by trevorbayless** [nickzuber/chs#13]
Issue #3 was merged, but a new release wasn't made. Therefore, when installing via `pip` chs will terminate with `FileNotFoundError`.

**Comment by BachoSeven** [comment]
This can be closed, since a new [version](https://github.com/nickzuber/chs/releases/tag/v2.2.2) was released.

**Comment by nickzuber** [comment]
Let me know if this still happens — I released a new version recently
