### ISSUE TITLE
Uncaught error "FileNotFoundError", exiting the app.

### ISSUE THREAD

**Issue by 9acca9** [nickzuber/chs#18]
I have that error when try to run from a raspbian.....
Thanks.

**Comment by BachoSeven** [comment]
This is a duplicate of https://github.com/nickzuber/chs/issues/3, and can be closed since this has been fixed and [released](https://github.com/nickzuber/chs/releases/tag/v2.2.2) as well.

**Comment by nickzuber** [comment]
Closing because a duplicate of #3 — I also released a new version recently, so hopefully that fixed it
