### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by deepend-tildeclub** [nickzuber/chs#3]
When I try to run chs it only comes back with a "Uncaught error "FileNotFoundError", exiting the app.

**Comment by deepend-tildeclub** [comment]
made it work by manually specifying the path to my local copy of stockfish in stockfish.py

**Comment by colinmcdonagh** [comment]
Yeah I have this error as well

**Comment by huytd** [comment]
OK, for those who got this error, we need to specify the full path to stockfish in stockfish.py.

On a Mac, it should be `/usr/local/bin/stockfish` (if you installed the engine from brew)
