### ISSUE TITLE
You cannot promote a pawn?

### ISSUE THREAD

**Issue by MathewPhew** [nickzuber/chs#34]
Is there a command to promote pawn or does it not exist?

**Comment by white-spaced** [comment]
In algebraic notation a pawn promotion is noted as "=X" at the end of the move before the check. X is the piece you want to promote. So, to promote a pawn on the e file that has taken a piece on f8 to a queen with check it would be "exf8=Q+".

**Comment by nickzuber** [comment]
Thank you @white-spaced — that's exactly correct 😄 

Closing since this isn't a bug!
