### ISSUE TITLE
Custom board size

### ISSUE THREAD

**Issue by jarun** [nickzuber/chs#5]
Would it be possible to customize the board size? On a high-res screen the board looks too small.

![](http://i.imgur.com/O2qYyWx.png)

**Comment by nickzuber** [comment]
This is an interesting idea — in general, I'd love something like that!

I think the tricky part here is the size of the board/pieces are relative to the size of the font in your terminal. I do wonder if there's some kind of workaround though 🤔

**Comment by nickzuber** [comment]
I've found zooming in helps increase the board size in the way you'd expect — seems like the simplest path forward for now
